[project]
name = "insurance-severity"
version = "0.1.14"
description = "ML PRO HW 1"
requires-python = ">=3.11,<3.13"

dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "pydantic-settings",
    "pandas",
    "scikit-learn>=1.6,<1.7",
    "joblib",
    "psycopg[binary]"
]

[dependency-groups]
dev = [
    "pytest",
    "httpx",
    "locust",
    "ruff",
]

[build-system]
requires = ["uv_build>=0.10,<0.11"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "severity"

[tool.pytest.ini_options]
testpaths = ["tests"]
